### ISSUE TITLE
Issue in Analysis 3

### ISSUE THREAD

**Issue by JTBrash** [oxford-pharmacoepi/RefractureStudy#2]
I am getting an error that I think is arising from Analysis_3/RQ1Characterization.R.
Screengrab of issue below, and link to problem code.

I think generateConceptCohortSet() expects a different order of arguments (basically, _codelistMedications_ and _medications_ should be switched - function screengrab below). When I switch the arguments, I run into a second error (below). I've not been able to isolate the cause of this error - is it an empty table?

Please note, I am not using DrugUtilisation v0.3.1 as specified in the renv, but I am instead using v 0.4.0.
There was a case error in 0.3.1 that had been resolved by v 0.4.0 - I'm unsure if the errors described below are thus a versioning issue.

**Code**
https://github.com/oxford-pharmacoepi/RefractureStudy/blob/c5182b88995948d41eb0c3767a49b7ce9560ede4/3_Analysis/RQ1Characterisation.R#L140C1-L140C89

**Error 1**

![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/6b5ff4b2-79d1-486d-ab5a-9b1139fff3c2)

**Function**
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/bacc7e33-dd3b-4ebb-8fab-86dbe832ec73)

**Error 2**
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/e48417f2-335a-4186-b584-21059b8fe7d9)

**Comment by xihang-chen** [comment]
Hi @JTBrash thanks for reporting this issue. Could you please share a screenshot what cdm_char_imm, medications and codelistMedications look like at your end? (over in R console please type cdm_char_imm for example, and press enter and could you please screenshot what the console outputs?)

My initial thought is that the version is most likely not an issue; as long as it is above v0.3.0 it should be fine.

**Comment by xihang-chen** [comment]
Hi @JTBrash I have also made some changes to the script so that the arguments should be in the right position. Could you please run the faulty line again to see if the problem persists? Thanks!

**Comment by JTBrash** [comment]
Hi @xihang-chen - I had ran the function with the correct position, but received error #2 from my original post.

**Comment by xihang-chen** [comment]
@JTBrash My apologies - I misread your initial post. In that case could you please screenshot what your cdm_char_imm currently looks like? Thanks!

**Comment by JTBrash** [comment]
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/bffa4ea6-28a4-4f90-9b5c-114d4014ba1e)

**Comment by xihang-chen** [comment]
Hi @JTBrash could I please check the version of CDMConnector that you are currently using? If it is at least 1.0.0 could I please ask you to do the following instead:
Replace the faulty line with cdm_char_imm <- generateDrugUtilisationCohortSet(cdm = cdm_char_imm, name = medications, conceptSet = codelistMedications)
Let me know if this works.
And as far as I am aware, generateConceptCohortSet is a CDMConnector function and it might fail on medications but it should be fine when it comes to conditions and so lines 144 to 145 should be fine.

**Comment by JTBrash** [comment]
Hi @xihang-chen , the above issue has resolved - but I have then hit an error further along Analysis #3 (so will continue logging to this issue). The error is shown below, and I believe the error arises from:
https://github.com/oxford-pharmacoepi/RefractureStudy/blob/c5182b88995948d41eb0c3767a49b7ce9560ede4/3_Analysis/RQ1Characterisation.R#L313

![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/d3f3d9e8-427e-4f23-9e4a-048a4d0ffd5a)

**Comment by xihang-chen** [comment]
Hi @JTBrash it is a bit difficult to say where it went wrong and so is it possible that you could please send me the three CSVs via email so that I could better investigate? Many thanks!

**Comment by xihang-chen** [comment]
Hi @JTBrash thanks for the CSVs, I had a look and realised that the formats are a bit different and so it threw an error. Nevertheless, I have managed to adapt my origin codes so that it should work now. So could you please do the following:
1. Update the functions.R file as I have written a tailored function (https://github.com/oxford-pharmacoepi/RefractureStudy/blob/main/Functions/functions.R#L316). Load this function into your R environment.
2. Now instead of that original line, do reformatted_table_1 <- reformat_table_one_iqvia(result_imm = result_imm, result_no_imm = result_no_imm, result_frac = result_frac)
I hope that should solve the issue, let me know if there are further issues.
Thanks!

**Comment by JTBrash** [comment]
Resolved
