### ISSUE TITLE
SelectedCovariates.R issues

### ISSUE THREAD

**Issue by JTBrash** [oxford-pharmacoepi/RefractureStudy#26]
Writing in response to this error I was getting:
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/cacadd21-02ba-4a17-95c5-c28f43d8404a)

The error is coming from this block:
https://github.com/oxford-pharmacoepi/RefractureStudy/blob/81edc561e0c853a1b6e07e5f7f118762125a0dff/Miscellaneous/SelectedCovariates.R#L13-L27

Specifically, the _cdm_database_schema_ . Because our write and cdm schemas are in different databases, we have to declare a 2 element vector of (<database>, <schema>) for cdm_database_schema. The above code takes each element separately and creates two lines of SQL:
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/667f2da4-06a4-4688-90cf-10038a8eb5ec)

That would need to be corrected (see possible solution below), but when I do amend and I run the code I run into some further issues due to the CASE of our columns in our snowflake database. The original code asks for columns names in lower case, but our columns are in upper case. I amended where needed below to get this block of code running, but I imagine this issue will pop up elsewhere:

selected01 <- selected01 %>% 
  dplyr::mutate(selected_covariates = as.integer(selected_covariates)) %>% 
  dplyr::rename("CONCEPT_ID" = "selected_covariates") %>% 
  left_join(tbl(db, sql(paste0(
    "SELECT * FROM ",
    paste0(cdm_database_schema[1], '.', cdm_database_schema[2]),
    ".concept"
  ))),
  copy = T) %>%
  dplyr::select(
    "CONCEPT_ID", "CONCEPT_NAME", "DOMAIN_ID", "VOCABULARY_ID", "period"
  ) %>%
  dplyr::collect() %>% 
  dplyr::rename("selected_covariates" = "CONCEPT_ID")

**Comment by xihang-chen** [comment]
Hey @JTBrash many thanks for raising this issue! I have since fixed the script so now it doesn't depend on such "sql-like" codes https://github.com/oxford-pharmacoepi/RefractureStudy/blob/main/Miscellaneous/SelectedCovariates.R#L16 could you please pull down the latest version and resume the run?
