### ISSUE TITLE
Health Economics - analyse_visits_cost(); two unit.cost columns

### ISSUE THREAD

**Issue by JTBrash** [oxford-pharmacoepi/RefractureStudy#27]
I've hit an error with the package:
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/6453b47b-de80-40be-b1f4-b3270da8a970)

The error stems from this line of code: 
https://github.com/oxford-pharmacoepi/RefractureStudy/blob/e79f9e1a207dc0418e9eeb49a8014990055f57a7/3_Analysis/RQ3HealthEconomics.R#L88

When I run the code up to this point I get the below table.
Thus, I think the problem is that there are two unit.cost columns, assumedly from an earlier join.
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/1933d7bc-1a9e-480c-9854-f724e6a9a389)

**Comment by xihang-chen** [comment]
Hi @JTBrash ! Many thanks for raising the issue! I have since made a change (in functions.R) to debug this issue, could you please pull the latest version and resume the run? Many thanks!
