### ISSUE TITLE
Error in 3_Analysis/RQ2IncidenceCalculation.R

### ISSUE THREAD

**Issue by JTBrash** [oxford-pharmacoepi/RefractureStudy#3]
Hit an error in RQ2IncidenceCalculation.R at this loop:
I've isolated the error to line 269.

https://github.com/oxford-pharmacoepi/RefractureStudy/blob/02d3667da8438a19d0b8e34590b8268f7aa22105/3_Analysis/RQ2IncidenceCalculation.R#L265-L280

Error running line 269:
![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/74d98c44-6fed-4ac2-8701-d2cbb3bfcf90)

Full error:

![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/88ec0572-2031-42a1-b88b-67a652436c0c)

**Comment by xihang-chen** [comment]
Hi @JTBrash as a first step, could I please check if length(hip_plots_data) is 0? So please run length(hip_plots_data) over your console and let me know if the output is 0. Also could you please let me know at which index i has this issue occurred? Thanks!

**Comment by JTBrash** [comment]
Hi @xihang-chen ,
index length = 2.
i = 2 at error

**Comment by xihang-chen** [comment]
Hi @JTBrash I have debugged the codes following our conversation last week. Could you please download the latest version of the package and let me know if this now works? Thanks!
