### ISSUE TITLE
Error in 3_Analysis /RQ2IncidenceCalculation.R - potentially because outcome count = 0

### ISSUE THREAD

**Issue by JTBrash** [oxford-pharmacoepi/RefractureStudy#4]
Logging the below error.
I think this is because there are no death records in this database, which causes an error when trying to create the survival plot (where imminent and death are outcomes).

![image](https://github.com/oxford-pharmacoepi/RefractureStudy/assets/114388547/daa31a66-f325-4bd9-ac70-4a757deb2843)

https://github.com/oxford-pharmacoepi/RefractureStudy/blob/37e1970b814027958eea6ee5ebaf184f0ac9933e/3_Analysis/RQ2IncidenceCalculation.R#L211-L214

**Comment by xihang-chen** [comment]
Hi @JTBrash agreed that this is most likely the issue. In that case could you please remove the death as an outcome? So could you please do this instead:

 first_plots[[1]]<-tidycmprsk::cuminc(Surv(follow_up_time, status) ~ 1, first_plots_data[[1]]) %>% 
   ggcuminc(outcome = c("imminent")) + 
   add_confidence_interval() + 
   theme(plot.title = element_text(hjust = 0.5)) 

Let me know if the error persists. Thanks!
